name: Docker Image Delivery

on:
  push:
    branches: [ "develop"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      #- name: Execute integration tests
      #  run: ./mvnw -B clean verify
      - name: Build & Push Docker image
        #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        run: ./mvnw -B package -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.password=${{ secrets.DOCKER_REGISTRY_CREDENTIALS }} -Dquarkus.docker.buildx.platform=linux/amd64,linux/arm64 --file pom.xml