name: Update Helm Image Tag Prod.

on:
  push:
    tags:
      - 'v*.*.*-prod'

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ env.IMAGE_TAG }}'
          separator: '-'
          maxsplit: 2
      - name: Trigger Helm Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.APIFORT_PAT }}
          repository: sitmena/delmonte-api-fort-charts
          event-type: apifort-delmonte-prod
          client-payload: '{"tag": "${{ steps.split.outputs._0 }}", "ref":"${{ github.ref }}", "sha": "${{ github.sha }}", "test": "Deploy Delmonte APIFort"}'
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: 'docker.io/sitmenadev/apifort-gateway:${{ steps.split.outputs._0 }}'
          format: 'table'
          security-checks: 'vuln'
          severity: 'HIGH,CRITICAL'
          vuln-type: 'os'
          exit-code: 1
        env:
          TRIVY_USERNAME: sitmenadev
          TRIVY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_CREDENTIALS }}
#      - name: Upload Trivy scan results to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: 'trivy-results.sarif'