name: Update Helm Image Tag.

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Trigger Helm Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.APIFORT_PAT }}
          event-type: apifort-delmonte
          client-payload: '{"tag": "${{ env.IMAGE_TAG }}", "ref":"${{ github.ref }}", "sha": "${{ github.sha }}", "test": "Deploy Delmonte APIFort"}'
