name: Update Helm Image Tag Prod.

on:
  push:
    tags:
      - 'v*.*.*-prod'

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ env.IMAGE_TAG }}'
          separator: '-'
          maxsplit: 2
      - name: Trigger Helm Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.APIFORT_PAT }}
          repository: sitmena/delmonte-api-fort-charts
          event-type: apifort-delmonte-prod
          client-payload: '{"tag": "${{ steps.split.outputs._0 }}", "ref":"${{ github.ref }}", "sha": "${{ github.sha }}", "test": "Deploy Delmonte APIFort"}'